Invalid add_to_cart_url & actionProductSave hook
PrestaShop/ps_featuredproducts pull request #32
Opened 2021-01-08 23:42 UTC by cryptoethic

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | solves two problems with cache (described below)
| Type?         | bug fix
| BC breaks?    |  no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Simple code to read ;-)

2 problems:
* add_to_cart_url has invalid token after login to different account.
* in prestashop 1.7.7.0 we need actionProductSave hook to recalculate featured products when something changes. (after changing visibility of product I had no changes in featured products section - I needed to clear cache)

2021-01-13 17:23 UTC, PierreRambaud requested changes
Hi, could you please rebase your pull request on the dev branch instead the master one?

2021-01-13 17:30 UTC, cryptoethic commented
Should the PR bee still into master branch or into dev branch?

2021-01-14 10:20 UTC, jf-viguier commented
This solution is too extreme, the cache will be empty too often, the cache should be customer dependant instead.
Related issue here https://github.com/PrestaShop/PrestaShop/issues/17111

2021-01-14 10:36 UTC, kpodemski commented
For the first issue, all you need to do is to alter code related to adding to cart, don't use token from your tpl, use token from `prestashop` JS variable

2021-01-14 13:17 UTC, cryptoethic commented
So my solution will not work correctly when we have two concurrent customers in the store. We will cache the token of the latest one.

So instead of hookActionAuthentication I suggest:

```php

    protected function getCacheId($name = null)
    { 
        $cacheId = parent::getCacheId($name); 
        if(isset($this->context->customer->id)){
            $cacheId .= '|'.$this->context->customer->id;
        } 
        return $cacheId;
    }

```

It will make cache customer dependant

2021-01-14 13:24 UTC, cryptoethic commented
And I have another question. Can customer token expire somehow? We should listen on such expiration and clear cache as well.

2021-01-14 14:15 UTC, jf-viguier commented
@kpodemski for the add to cart is not possible, the js logic is in the core.js

2021-01-14 14:21 UTC, kpodemski commented
@jf-viguier I know, it's core issue but of course adding to cart can be separated off the core if developer wants, I think issue with customer token is easiest one, but things related to SpecificPrice and taxes are tricky

2021-01-14 14:29 UTC, jf-viguier commented
> Can customer token expire somehow?
@cryptoethic : no, it's a hash made with login and password. If the customer change his password, the token will change.
Do we really need cache for this module ?

2021-01-14 17:33 UTC, cryptoethic commented
Well then can you spot any problems with the proposed solution of cache per customer?

2021-01-14 17:34 UTC, PierreRambaud commented
Closed in favor of #33

2021-01-14 17:34 UTC, closed without merging